### ISSUE TITLE
问下EvaEngine有分表的功能吗?

### ISSUE THREAD

**Issue by PoplarDddCN** [EvaEngine/EvaEngine#10]
问下EvaEngine有分表的功能吗?比如根据ID范围来分表：
```php
function getTable( $uid ){
  $ext =  substr ( md5($uid) ,0 ,2 );
  return "user_".$ext;
}
```
EvaEngine有这种功能吗？

**Comment by AlloVince** [comment]
可以自己继承`Eva\EvaEngine\Mvc\Model`然后覆盖`getSource`方法

**Comment by PoplarDddCN** [comment]
AlloVince类似下面这样吗？

```php
class Users extends Eva\EvaEngine\Mvc\Model {
    public function getSource () {
       $ext =  substr(md5($uid), 0, 2);//通过UID来拼接用户表
       $this->setSource('users_' . $ext);
    }
}
```

问题没搞清楚 `uid` 是在什么时候传到 `getSource()` 方法里？还请劳驾讲一下，先谢谢啦！

**Comment by AlloVince** [comment]
可以参考这个实现
http://stackoverflow.com/questions/22215688/how-to-connect-multiple-database-in-phalcon-framework-at-the-same-time-use-both
