### ISSUE TITLE
Failed to clone https://github.com/EvaEngine/incubator.git

### ISSUE THREAD

**Issue by smelike** [EvaEngine/EvaEngine#12]
今天下载了你的EvaEngine代码，想要跑起来试一试。在我执行 php composer.php install 时，出现报错提示：Failed to clone https://github.com/EvaEngine/incubator.git, git was not found, check that it is installed and in your PATH env.

**Comment by ZhenhangTong** [comment]
2个方案：

- 你先安装Git

- 跑composer install时候加上--prefer-dist参数，参考[composer-says-git-not-found](http://stackoverflow.com/questions/17792588/composer-says-git-not-found)
