### ISSUE TITLE
请问EvaEngine支持php7了吗？

### ISSUE THREAD

**Issue by PoplarDddCN** [EvaEngine/EvaEngine#17]
最近把php5升级到了php7，在跑EvaEngine的时候，http返回状态码200，但是问题浏览器没有响应内容，response为空，php.ini错误都开启了，发起http请求EvaEngine还是没有任何响应输出，请问你知道是怎么回事吗？

**Comment by AlloVince** [comment]
应该是Phalcon本身的问题，EvaEngine没有做兼容的处理，暂时也没有相关的计划，欢迎PR
