### ISSUE TITLE
phalcon 2.0.8的兼容性问题

### ISSUE THREAD

**Issue by songrgg** [EvaEngine/EvaEngine#7]
Phalcon 2.0.8里Phalcon\Mvc\Model\Validator\Uniqueness类的validate方法的参数声明类型为Phalcon\Mvc\EntityInterface，需要更新下Eva\EvaEngine\Mvc\Model\Validator\Uniqueness中的validate声明。

Phalcon 2.0.x:
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model/validator/uniqueness.zep

**Comment by AlloVince** [comment]
发个pull request来
